In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

## Data Encoding :- 
`Converting the categorical values into numerical values so that the model is able to understand and differentiate`

#### Ways to do it :- 
1. Nominal or one Hot Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding


****************************************************************************

### Nominal / One-Hot Encoding
`Definition`: A technique to convert categorical (nominal) data into a numerical format for Machine Learning models. It creates a binary column for every unique category in a feature.

How it Works: If a feature "Color" has 3 categories: Red, Blue, Green:

Red becomes [1, 0, 0]

Blue becomes [0, 1, 0]

Green becomes [0, 0, 1]

### Disadvantages
`Sparse Matrix`: Since only one value is "1" and the rest are "0," the resulting table is mostly empty (zeros), which is memory-inefficient.

`Feature Explosion`: If a column has high cardinality (e.g., 500 unique Cities), One-Hot Encoding adds 500 new features, leading to the Curse of Dimensionality.

`Multicollinearity (Dummy Variable Trap)`: One feature can be predicted from the others (e.g., if it’s not Red or Blue, it must be Green).

Fix: Use drop_first=True to remove one redundant column.


#### When to Use
> When categories have no natural order (e.g., Countries, Colors).

> When the number of unique categories is low (typically < 10-15).

In [3]:
from sklearn.preprocessing import OneHotEncoder

In [4]:
## Create a Simple dataFrame
df = pd.DataFrame({
    'Color' : ['Red' , 'Green' , 'Blue' , 'Blue' , 'Green' , 'Red']
})

df

   Color
0    Red
1  Green
2   Blue
3   Blue
4  Green
5    Red

In [5]:
## Create an instance of OneHotEncoder 
encoder = OneHotEncoder()

In [6]:
color_encoded = encoder.fit_transform(df[['Color']]).toarray()

### columns = encoder.get_feature_names_out()
The method looks at the original column name and the unique categories inside it to create a list of strings.

Original Data: A column named Color with categories Red, Green, and Blue.

Method Output: A list: ['Color_Red', 'Color_Green', 'Color_Blue'].

In [7]:
encoder_df = pd.DataFrame(color_encoded , columns = encoder.get_feature_names_out())

In [8]:
encoder_df

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         1.0          0.0        0.0
4         0.0          1.0        0.0
5         0.0          0.0        1.0

In [9]:
## For new data 
encoder.transform([['Blue']]).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [10]:
pd.concat([df , encoder_df] , axis = 1)

   Color  Color_Blue  Color_Green  Color_Red
0    Red         0.0          0.0        1.0
1  Green         0.0          1.0        0.0
2   Blue         1.0          0.0        0.0
3   Blue         1.0          0.0        0.0
4  Green         0.0          1.0        0.0
5    Red         0.0          0.0        1.0

# Label Encoding :- 
 `Definition`: A technique used to convert categorical text labels into numerical values. Each unique category is assigned an integer (e.g., 0, 1, 2) based on alphabetical order.

In [11]:
from sklearn.preprocessing import LabelEncoder 
lbl_encoder = LabelEncoder()

In [12]:
df

   Color
0    Red
1  Green
2   Blue
3   Blue
4  Green
5    Red

In [13]:
lbl_encoder.fit_transform(df[['Color']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 1, 0, 0, 1, 2])

In [14]:
lbl_encoder.transform([['Red']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

## Ordinal Encoding 
It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have a categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High school: 1
2. College: 2
3. Graduate: 3
4. Post-graduate: 4

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
df = pd.DataFrame({
    'Size' : ['Small' , 'Large' , 'Small' , 'Medium' , 'Large']
})

In [17]:
df

     Size
0   Small
1   Large
2   Small
3  Medium
4   Large

In [18]:
encoder = OrdinalEncoder(categories = [['Small' , 'Medium' , 'Large']])

In [19]:
encoder.fit_transform(df[['Size']])

array([[0.],
       [2.],
       [0.],
       [1.],
       [2.]])

In [20]:
encoder.transform([['Small']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

## Target Guided Ordinal Encoding

In [21]:
data = {
    'City': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', 'Bangalore', 'Delhi', 'Mumbai', 'Chennai'],
    'Price': [12000, 15000, 18000, 12500, 17500, 14800, 12200, 11000]
}

In [22]:
df = pd.DataFrame(data)
df

        City  Price
0     Mumbai  12000
1      Delhi  15000
2  Bangalore  18000
3     Mumbai  12500
4  Bangalore  17500
5      Delhi  14800
6     Mumbai  12200
7    Chennai  11000

In [23]:
mean_price = df.groupby('City')['Price'].mean().to_dict()
mean_price

{'Bangalore': 17750.0,
 'Chennai': 11000.0,
 'Delhi': 14900.0,
 'Mumbai': 12233.333333333334}

In [24]:
df['City_Encoded'] = df['City'].map(mean_price)

In [25]:
df

        City  Price  City_Encoded
0     Mumbai  12000  12233.333333
1      Delhi  15000  14900.000000
2  Bangalore  18000  17750.000000
3     Mumbai  12500  12233.333333
4  Bangalore  17500  17750.000000
5      Delhi  14800  14900.000000
6     Mumbai  12200  12233.333333
7    Chennai  11000  11000.000000

In [26]:
df[['City' , 'City_Encoded']]

        City  City_Encoded
0     Mumbai  12233.333333
1      Delhi  14900.000000
2  Bangalore  17750.000000
3     Mumbai  12233.333333
4  Bangalore  17750.000000
5      Delhi  14900.000000
6     Mumbai  12233.333333
7    Chennai  11000.000000

In [27]:
tips = sns.load_dataset('tips')

In [28]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
tips.time.value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [30]:
mean_bill = tips.groupby('time')['total_bill'].mean().to_dict()

/tmp/ipykernel_16/1418129760.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill = tips.groupby('time')['total_bill'].mean().to_dict()

In [31]:
tips['Dinner_encoded'] = tips['time'].map(mean_bill)

In [32]:
tips.head()

   total_bill   tip     sex smoker  day    time  size Dinner_encoded
0       16.99  1.01  Female     No  Sun  Dinner     2      20.797159
1       10.34  1.66    Male     No  Sun  Dinner     3      20.797159
2       21.01  3.50    Male     No  Sun  Dinner     3      20.797159
3       23.68  3.31    Male     No  Sun  Dinner     2      20.797159
4       24.59  3.61  Female     No  Sun  Dinner     4      20.797159